# infrastructure/monitoring/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'orchestrator-dev'

# Load alert rules
rule_files:
  - "alert-rules.yml"

# Scrape configurations
scrape_configs:
  # Orchestrator metrics
  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:8000']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # Celery metrics (if using celery-prometheus-exporter)
  - job_name: 'celery'
    static_configs:
      - targets: ['celery-worker:9540']
    scrape_interval: 15s

  # PostgreSQL metrics (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
    scrape_interval: 15s

  # Redis metrics (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121', 'redis-cache:9121']
    scrape_interval: 15s

  # System metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s